### PR TITLE
fixes: playlist video queueing and inactivity check

### LINKED ISSUE #1183: Bug: Queueing a playlist result in only 1 song played
**Describe the bug**
The bot failed to retrieve playlist songs, it only queue 1 song

**How To Reproduce**
1. Run the bot as usual
2. Try to queue a playlist
3. Check the queue list with !queue
 
**Expected behavior**
The bot should queue every songs there are in the playlist

**Environment (add if possible)**
* Node.js version: v16.11.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
image

### PR DESCRIPTION
**Pull request by nikosszzz**
* Fixes the playlist command only queueing one song from the given playlist when theres no queue.

* Fixes the inactivity check leaving even if the queue is playing.

* Closes #1183, #1212

### CODE REVIEW

**Review by Gamebuster19901 — APPROVED** [review]

File: commands/playlist.ts [hunk 1]
```diff
@@ -50,6 +50,8 @@ export default {
       });
 
       bot.queues.set(message.guild!.id, newQueue);
+      newQueue.songs.push(...playlist.videos);
+      
       newQueue.enqueue(playlist.videos[0]);
```
Comment (Gamebuster19901) [inline commands/playlist.ts:55]: This adds the first song in the playlist into the queue twice.

**Review by Gamebuster19901 — CHANGES_REQUESTED** [review]

File: commands/playlist.ts (hunk 1 above)
Comment (nikosszzz) [reply commands/playlist.ts:55]: Hm, could the enqueue part be removed since i’m pushing the songs, or no?

Comment (nikosszzz) [reply commands/playlist.ts:55]: Actually, upon testing that is false. It does not add the first song twice.
